version: "3"
services:
  server:
      image: ubuntu:latest
      container_name: test_server
      ports:
        - 80:80
      volumes:
        - ./maestro.tar:/tmp/maestro.tar
        - ./startup.sh:/tmp/startup.sh
      command: ["sleep","infinity"]