---  
  files:
    file_php:
      filename: "index.php"
      permissions: 0644
      user: root
      group: root
      filelocation: "/var/www/html/index.php"
      service: "apache2"
    file_apache_conf:
      filename: "dir.conf"
      permissions: 0644
      user: root
      group: root
      filelocation: "/etc/apache2/mods-enabled/dir.conf"
      service: "apache2"
  packages:
    package_php:
      service: "php"
      packagename: "php"
      action: install
    package_php_apache:
      service: "apache2"
      packagename: "libapache2-mod-php"
      action: install
  services:
    service_apache2:
      servicename: apache2
      action: running
      restartcommand: "apachectl -k restart"